const sidebars = {
    docs: [
        {
            type: 'autogenerated',
            dirName: 'en',
        },
    ],

    chinese: [
        {
            type: 'autogenerated',
            dirName: 'zh',
        },
    ],
};

module.exports = sidebars;
