const sidebars = {
    docs: [
        {
            type: 'autogenerated',
            dirName: 'en',
        },
    ],

    // Commenting this section out to remove the "can't auto-generate a sidebar" warning.
    // chinese: [
    //     {
    //         type: 'autogenerated',
    //         dirName: 'zh',
    //     },
    // ],
};

module.exports = sidebars;
